### ISSUE TITLE
Any way to iterate array and object?

### ISSUE THREAD

**Issue by miloyip** [nbsdx/SimpleJSON#1]

**Comment by nbsdx** [comment]
Pushed an update for this, iterators exposed through the "ArrayRange" and "ObjectRange" functions. Let me know if anything doesn't work.

**Comment by miloyip** [comment]
I have tested them and they work.
Besides, I also find that `JSONType()` and `IsNull()` should be const functions.
Also, `operator[]`, `ArrayRange()` and `ObjectRange()` functions should also have const version.

**Comment by nbsdx** [comment]
Fixed, with the exception that `operator[]` doesn't have a `const` version, use `JSON::at()` instead, as it's more in line with STL const conventions.
