### ISSUE TITLE
Academic citation

### ISSUE THREAD

**Issue by sjgardiner** [nbsdx/SimpleJSON#17]
Hi @nbsdx, I'm a postdoctoral researcher at Fermilab (a department of energy laboratory in the Chicago suburbs). I'm working on a journal publication describing a physics simulation tool called MARLEY. A few years ago I found this repo and adapted your SimpleJSON code into a configuration file parser for MARLEY (here's the altered code if you're curious: https://github.com/sjgardiner/marley/blob/master/include/marley/JSON.hh). Thanks for sharing your work, it saved me a lot of pain!

I'd like to cite the SimpleJSON library in my journal article, which includes a lot of material about implementation details. Would you please email me when you get the chance (my address is my last name "@fnal.gov") and let me know what author name I should use in the bibliography? If possible, I'd really like to give you credit for your hard work.

**Comment by nbsdx** [comment]
Hi @sjgardiner! I sent you an email with my full name from my work email. Let me know if you don't get it.

Thanks!
Neil
