### ISSUE TITLE
No license information available

### ISSUE THREAD

**Issue by valkenburg** [nbsdx/SimpleJSON#2]
Can I include the source in an open source project, and redistribute the source, with due acknowledgements, under a 
Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International Public License
http://creativecommons.org/licenses/by-nc-sa/4.0/legalcode
http://creativecommons.org/licenses/by-nc-sa/4.0/
 ?

**Comment by nbsdx** [comment]
Sorry, I've been meaning to add the license to it, I'll update it tomorrow. It'll be under the BSD 2 clause license. 

http://opensource.org/licenses/BSD-2-Clause

**Comment by lefticus** [comment]
Yes, please provide the license so we can be clear. Thanks.

**Comment by nbsdx** [comment]
Updated README.
